keys:
  - &windstorm age1nk7x6czlkhueecs36vq3m2aw22rgzp4pehzpff2048p67unz5a4sxvfr0u
  - &prowler age1dwat457ny5pec53gjd6v292sdxhzz74uksxp7yxshdj5p87p6ymsvtursp
  - &rendezvous age1rj28y40tzyg6dkkfaud9xzt3d08qu85tvjtzsnuuyncg4flfychsvyvev6
  - &nightcrawler age1gelcfus7vuk0n0lwnqtuwemrfttd9cq4d4tx5aqzvsslrskv9d4sak77cc
creation_rules:
  - path_regex: ^secrets/common.yaml$
    key_groups:
    - age:
      - *windstorm
      - *prowler
      - *rendezvous
      - *nightcrawler
  - path_regex: ^secrets/desktop.yaml$
    key_groups:
    - age:
      - *windstorm
      - *nightcrawler
