keys:
  - &yubikey0 age1yubikey1q07354szx8u0lguhn7dwasfpddvn5zn64fygpge780vzqj6x025eqnmw9j6
  - &yubikey1 age1yubikey1qwnxgj05unlv7y75t2t88mfftxq7uqmjdxsfky4t0v6qg623rhdv24sy554
  - &windstorm age1nk7x6czlkhueecs36vq3m2aw22rgzp4pehzpff2048p67unz5a4sxvfr0u
  - &prowler age1dwat457ny5pec53gjd6v292sdxhzz74uksxp7yxshdj5p87p6ymsvtursp
  - &rendezvous age1rj28y40tzyg6dkkfaud9xzt3d08qu85tvjtzsnuuyncg4flfychsvyvev6
  - &nightcrawler age1gelcfus7vuk0n0lwnqtuwemrfttd9cq4d4tx5aqzvsslrskv9d4sak77cc
  - &iridescent age1jks4y76jn0gj93n3aax7tqpuuq3cgns54434vsxj29ee38rqzadsc9myks
creation_rules:
  - path_regex: ^secrets/common.yaml$
    key_groups:
    - age:
      - *yubikey0
      - *yubikey1
      - *windstorm
      - *prowler
      - *rendezvous
      - *nightcrawler
      - *iridescent
  - path_regex: ^secrets/desktop.yaml$
    key_groups:
    - age:
      - *yubikey0
      - *yubikey1
      - *windstorm
      - *nightcrawler
