[org-bleeding-latex]
src.git = "https://code.tecosaur.net/tec/org-mode.git"
src.branch = "dev"
fetch.git = "https://code.tecosaur.net/tec/org-mode.git"

[org-popup-posframe]
src.git = "https://github.com/A7R7/org-popup-posframe"
fetch.github = "A7R7/org-popup-posframe"

[org-typst]
src.git = "https://github.com/skissue/org-typst"
fetch.github = "skissue/org-typst"

[gptel-quick]
src.git = "https://github.com/karthink/gptel-quick"
fetch.github = "karthink/gptel-quick"

[consult-omni]
src.git = "https://github.com/armindarvish/consult-omni"
fetch.github = "armindarvish/consult-omni"

[consult-mu]
src.git = "https://github.com/armindarvish/consult-mu"
fetch.github = "armindarvish/consult-mu"

[revealjs]
src.github_tag = "hakimel/reveal.js"
fetch.github = "hakimel/reveal.js"

[org-modern-indent]
src.git = "https://github.com/jdtsmith/org-modern-indent"
fetch.github = "jdtsmith/org-modern-indent"

[mpv-skipsilence]
src.git = "https://codeberg.org/ferreum/mpv-skipsilence"
fetch.git = "https://codeberg.org/ferreum/mpv-skipsilence"

[ultra-scroll]
src.git = "https://github.com/jdtsmith/ultra-scroll"
fetch.github = "jdtsmith/ultra-scroll"

[inline-diff]
src.git = "https://code.tecosaur.net/tec/inline-diff.git"
fetch.git = "https://code.tecosaur.net/tec/inline-diff.git"
