# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  consult-mu = {
    pname = "consult-mu";
    version = "8b54bbf86c2f112e3520eeeefb70d509b4590385";
    src = fetchFromGitHub {
      owner = "armindarvish";
      repo = "consult-mu";
      rev = "8b54bbf86c2f112e3520eeeefb70d509b4590385";
      fetchSubmodules = false;
      sha256 = "sha256-nxutBOEO6qiPjSo7y3t1KWYb0n0AMKGl943N+uGTTjQ=";
    };
    date = "2025-12-02";
  };
  consult-omni = {
    pname = "consult-omni";
    version = "3a126ee54479755408faed10da945dbc2366303b";
    src = fetchFromGitHub {
      owner = "armindarvish";
      repo = "consult-omni";
      rev = "3a126ee54479755408faed10da945dbc2366303b";
      fetchSubmodules = false;
      sha256 = "sha256-8Koe6IO2+/HvDb2IE1dc/DY3hGmNWcEMAfz6d0gdT7k=";
    };
    date = "2026-06-24";
  };
  elfin = {
    pname = "elfin";
    version = "cf5c4d24239822aaf868d72b506b5c2bcadd50e7";
    src = fetchFromGitHub {
      owner = "skissue";
      repo = "elfin";
      rev = "cf5c4d24239822aaf868d72b506b5c2bcadd50e7";
      fetchSubmodules = false;
      sha256 = "sha256-tztqNqwvW3b7fCEd5T0fys8rcMuDTVrQOSNMcMuYci0=";
    };
    date = "2026-04-27";
  };
  gptel-openrouter-models = {
    pname = "gptel-openrouter-models";
    version = "5ed8b75b371f3dafe05bbc6ec9bf623ad49e3f06";
    src = fetchFromGitHub {
      owner = "skissue";
      repo = "gptel-openrouter-models";
      rev = "5ed8b75b371f3dafe05bbc6ec9bf623ad49e3f06";
      fetchSubmodules = false;
      sha256 = "sha256-kIP8z/NZyiyTGuMBygAsJE8aSG2fwo+F3pKe8wxeLZM=";
    };
    date = "2026-10-03";
  };
  gptel-quick = {
    pname = "gptel-quick";
    version = "36fe296e016449433fa1213f4b89cb8dc7d4db5e";
    src = fetchFromGitHub {
      owner = "karthink";
      repo = "gptel-quick";
      rev = "36fe296e016449433fa1213f4b89cb8dc7d4db5e";
      fetchSubmodules = false;
      sha256 = "sha256-W2cEtjhoXxAhMxycLAg0qe2Ehpgn1L/m1VcpZu/Trsw=";
    };
    date = "2026-06-07";
  };
  howm = {
    pname = "howm";
    version = "565f0d174017bc45ea9d3527a43e29c5f4437559";
    src = fetchFromGitHub {
      owner = "skissue";
      repo = "howm";
      rev = "565f0d174017bc45ea9d3527a43e29c5f4437559";
      fetchSubmodules = false;
      sha256 = "sha256-9xhrJ5eTYCyLd9LJkdgkDUpq5VtypY1iybNMB3nLlMI=";
    };
    date = "2026-03-12";
  };
  inline-diff = {
    pname = "inline-diff";
    version = "d1c13190dd9d8f5d14b52499ddfbcadba2a60e94";
    src = fetchgit {
      url = "https://code.tecosaur.net/tec/inline-diff.git";
      rev = "d1c13190dd9d8f5d14b52499ddfbcadba2a60e94";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-DbInB73UmMoqU1nJWJocKinJSUqxbY8tzLS0j8gq4FU=";
    };
    date = "2025-03-23";
  };
  modus-alabaster = {
    pname = "modus-alabaster";
    version = "29369bf9900f1511be20f3021bde0bbe56dc3b28";
    src = fetchFromGitHub {
      owner = "dpassen";
      repo = "modus-alabaster";
      rev = "29369bf9900f1511be20f3021bde0bbe56dc3b28";
      fetchSubmodules = false;
      sha256 = "sha256-XOJweRwVn7t4jPMg9GXiZlqGi8e0ccf7sstwZLBHPp0=";
    };
    date = "2026-10-02";
  };
  org-modern-indent = {
    pname = "org-modern-indent";
    version = "86bd83ee1ad95f123810eb3b116beb543db1960a";
    src = fetchFromGitHub {
      owner = "jdtsmith";
      repo = "org-modern-indent";
      rev = "86bd83ee1ad95f123810eb3b116beb543db1960a";
      fetchSubmodules = false;
      sha256 = "sha256-vQzYk5qejCBehpbxkMceOMsmeLyjnAstpezZw/ZR1jQ=";
    };
    date = "2026-07-21";
  };
  org-typst = {
    pname = "org-typst";
    version = "a9a8f2ebd227f5f170cd14318cb755f5e4306223";
    src = fetchFromGitHub {
      owner = "skissue";
      repo = "org-typst";
      rev = "a9a8f2ebd227f5f170cd14318cb755f5e4306223";
      fetchSubmodules = false;
      sha256 = "sha256-6DCttkycX62ungFsZ5lwb2fCYUJKrbfCAf5+YBSWkN4=";
    };
    date = "2026-09-29";
  };
  qml-ts-mode = {
    pname = "qml-ts-mode";
    version = "b80c6663521b4d0083e416e6712ebc02d37b7aec";
    src = fetchFromGitHub {
      owner = "xhcoding";
      repo = "qml-ts-mode";
      rev = "b80c6663521b4d0083e416e6712ebc02d37b7aec";
      fetchSubmodules = false;
      sha256 = "sha256-WXK/CdFF9E2kG+uIios4HtKcEMhILS9MddJfVDeRLh0=";
    };
    date = "2025-06-01";
  };
  revealjs = {
    pname = "revealjs";
    version = "6.0.2";
    src = fetchFromGitHub {
      owner = "hakimel";
      repo = "reveal.js";
      rev = "6.0.2";
      fetchSubmodules = false;
      sha256 = "sha256-yh9Fwp8PT6fFrbSsih7cD9EzH2wbfd3idjyemOQTqF8=";
    };
  };
  vertico-popup-frame = {
    pname = "vertico-popup-frame";
    version = "15e4969622bbfe6d699e6e4fab4ac3b7d9c20bf9";
    src = fetchFromGitHub {
      owner = "skissue";
      repo = "vertico-popup-frame";
      rev = "15e4969622bbfe6d699e6e4fab4ac3b7d9c20bf9";
      fetchSubmodules = false;
      sha256 = "sha256-EZ7H/kDyEJOa+JTZzjqf6Oa0UfP1eLAyVZfvGxQweHE=";
    };
    date = "2026-05-28";
  };
}
