# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  consult-mu = {
    pname = "consult-mu";
    version = "4958fb651917b0f9f79f436f7a753263c8003537";
    src = fetchFromGitHub {
      owner = "armindarvish";
      repo = "consult-mu";
      rev = "4958fb651917b0f9f79f436f7a753263c8003537";
      fetchSubmodules = false;
      sha256 = "sha256-cRFYTnfwWz4bxCirDHJ43Vw3eAYthJ5auRHLd+Cgo5c=";
    };
    date = "2025-06-17";
  };
  consult-omni = {
    pname = "consult-omni";
    version = "9fb21c08ed0f836727f2d325516e3232ce31ef97";
    src = fetchFromGitHub {
      owner = "armindarvish";
      repo = "consult-omni";
      rev = "9fb21c08ed0f836727f2d325516e3232ce31ef97";
      fetchSubmodules = false;
      sha256 = "sha256-ghFB5NiheDO01I1quQywu8Sz+yWruYP/S00sm+aewMY=";
    };
    date = "2025-09-27";
  };
  gptel-quick = {
    pname = "gptel-quick";
    version = "018ff2be8f860a1e8fe3966eec418ad635620c38";
    src = fetchFromGitHub {
      owner = "karthink";
      repo = "gptel-quick";
      rev = "018ff2be8f860a1e8fe3966eec418ad635620c38";
      fetchSubmodules = false;
      sha256 = "sha256-7a5+YQifwtVYHP6qQXS1yxA42bVGXmErirra0TrSSQ0=";
    };
    date = "2025-11-05";
  };
  inline-diff = {
    pname = "inline-diff";
    version = "d1c13190dd9d8f5d14b52499ddfbcadba2a60e94";
    src = fetchgit {
      url = "https://code.tecosaur.net/tec/inline-diff.git";
      rev = "d1c13190dd9d8f5d14b52499ddfbcadba2a60e94";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-DbInB73UmMoqU1nJWJocKinJSUqxbY8tzLS0j8gq4FU=";
    };
    date = "2025-03-23";
  };
  org-bleeding-latex = {
    pname = "org-bleeding-latex";
    version = "f9f909681a051c73c64cc7b030aa54d70bb78f80";
    src = fetchgit {
      url = "https://code.tecosaur.net/tec/org-mode.git";
      rev = "f9f909681a051c73c64cc7b030aa54d70bb78f80";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-MbXBcN6PJ1YSZCyxrg5Fng9pVY9X5FHFB+KAFwQu7zQ=";
    };
    date = "2025-08-10";
  };
  org-modern-indent = {
    pname = "org-modern-indent";
    version = "9973bd3b91e4733a3edd1fca232208c837c05473";
    src = fetchFromGitHub {
      owner = "jdtsmith";
      repo = "org-modern-indent";
      rev = "9973bd3b91e4733a3edd1fca232208c837c05473";
      fetchSubmodules = false;
      sha256 = "sha256-st3338Jk9kZ5BLEPRJZhjqdncMpLoWNwp60ZwKEObyU=";
    };
    date = "2025-04-12";
  };
  org-popup-posframe = {
    pname = "org-popup-posframe";
    version = "d39cb7c2c9a996689b0d6519695eed3d807c0c85";
    src = fetchFromGitHub {
      owner = "A7R7";
      repo = "org-popup-posframe";
      rev = "d39cb7c2c9a996689b0d6519695eed3d807c0c85";
      fetchSubmodules = false;
      sha256 = "sha256-yZJBx/uJ9W9ZAdYieZ7ArRvigt0391rIyTt+DEIHHjU=";
    };
    date = "2024-05-28";
  };
  org-typst = {
    pname = "org-typst";
    version = "367f23c9db3c80f75be6c407470ba71d5c34f709";
    src = fetchFromGitHub {
      owner = "skissue";
      repo = "org-typst";
      rev = "367f23c9db3c80f75be6c407470ba71d5c34f709";
      fetchSubmodules = false;
      sha256 = "sha256-ynuUyRdZRvmUq/zejkGyZSpHDKd7R34olAfqMoqU7Ic=";
    };
    date = "2024-05-10";
  };
  revealjs = {
    pname = "revealjs";
    version = "5.2.1";
    src = fetchFromGitHub {
      owner = "hakimel";
      repo = "reveal.js";
      rev = "5.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-f5g09Xj4XF+v6Y6zW13R4PUTWkAt3wwGpa9nSypUV6w=";
    };
  };
  ultra-scroll = {
    pname = "ultra-scroll";
    version = "f990ae3c0344ac1d8f976d62265d154959280581";
    src = fetchFromGitHub {
      owner = "jdtsmith";
      repo = "ultra-scroll";
      rev = "f990ae3c0344ac1d8f976d62265d154959280581";
      fetchSubmodules = false;
      sha256 = "sha256-RRmD+4w48xpl3M/sNQwEV+P6q5N+xYAkEb/UyX03X9I=";
    };
    date = "2025-11-08";
  };
}
